Adding a new "Replace" normalizer that takes a string and replaces it
huggingface/tokenizers pull request #417
Opened 2020-09-16 09:15 UTC by Narsil

with another String (for now).
Fixes #414

2020-09-16 12:43 UTC, n1t0 requested changes
Nice! We can probably already make it generic over `Pattern` in Rust, we just miss some stuff to implement the Python bindings at the moment.

2020-09-16 12:43 UTC, n1t0 commented on bindings/python/src/normalizers.rs
> +    fn new(pattern: &PyString, content: &PyString) -> PyResult<(Self, PyNormalizer)> {
No need to convert manually, you can do:
```rust
fn new(pattern: String, content: String) -> PyResult<(Self, PyNormalizer)> {
```

2020-09-16 12:43 UTC, n1t0 commented on tokenizers/src/normalizers/replace.rs
> +        normalized.replace(pattern, &self.content)?;
You can directly return `normalized.replace(...)` here.

2020-09-18 07:23 UTC, Narsil commented
Given that it's relatively hard to put directly a pattern here, can we move this forward for now so we can get `tokenizers` fast into transformers first, then figure out how to make it generic in another issue/PR ?

2020-09-18 10:24 UTC, merged